<%@ Page Title="" Language="C#" MasterPageFile="~/admin.Master" AutoEventWireup="true" CodeBehind="Viewcategories.aspx.cs" Inherits="furnitur_website2.Viewcategories" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <h1 class="text-center">View all Categories</h1>
    <div class="container">
        <div class="row" >
            <div class="col-md-10 mx-auto">
                 <div class="row">
                            <div class="col-md-12">
                                <hr />
                            </div>
                        </div>
                <div class="row">
                    <div class="col-6">
                        <label>Main category</label>
                    </div>
                    <div class="col-6">
                        <asp:DropDownList ID="Ddlcategory" runat="server" AutoPostBack="True" OnSelectedIndexChanged="Ddlcategory_SelectedIndexChanged">
                            <asp:ListItem>Chairs</asp:ListItem>
                            <asp:ListItem>Tables</asp:ListItem>
                            <asp:ListItem>SoFa</asp:ListItem>
                            <asp:ListItem>Beds</asp:ListItem>
                        </asp:DropDownList>
                    </div>
                        </div>
                <div class="row">
                    <div class="col-md-12">
                        <hr />
                        <hr />
                    </div>
                </div>
                 <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#333333" CssClass="table table-bordered" DataKeyNames="maincategory,categoryname" DataSourceID="SqlDataSource1" Font-Bold="False" HorizontalAlign="Center" AllowPaging="True" AutoGenerateDeleteButton="True">
                                <Columns>
                                    <asp:BoundField DataField="maincategory" HeaderText="maincategory" ReadOnly="True" SortExpression="maincategory" />
                                    <asp:BoundField DataField="categoryname" HeaderText="categoryname" ReadOnly="True" SortExpression="categoryname" />
                                </Columns>
                                <HeaderStyle BackColor="Silver" />
                            </asp:GridView>
                            </div>
                        </div>
                     </div>

                </div>
            </div>
        </div>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:fdconnectionstring %>" SelectCommand="SELECT * FROM [category] WHERE ([maincategory] = @maincategory)" DeleteCommand="DELETE FROM [category] WHERE [maincategory] = @maincategory AND [categoryname] = @categoryname" InsertCommand="INSERT INTO [category] ([maincategory], [categoryname]) VALUES (@maincategory, @categoryname)">
        <DeleteParameters>
            <asp:ControlParameter ControlID="Ddlcategory" Name="maincategory" PropertyName="SelectedValue" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="maincategory" Type="String" />
            <asp:Parameter Name="categoryname" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="Ddlcategory" Name="maincategory" PropertyName="SelectedValue" Type="String" />
        </SelectParameters>
     </asp:SqlDataSource>
</asp:Content>
